config/routes.rb
Rails.application.routes.draw do
  get 'greeter/hello' => "greeter#hello"    # the # symbols shows that this is an action (method)

  get 'greeter/goodbye' => "greeter#goodbye"

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/greeter_controller.rb
class GreeterController < ApplicationController
  def hello
  	random_names = ['Alex', 'Michael', 'Joe']
  	@name = random_names.sample
  	@time = Time.now
  	@times_displayed ||= 0
  	@times_displayed +=1
  end
  def goodbye
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/greeter_helper.rb
module GreeterHelper
	def formatted_time(time)
		time.strftime("%I:%M %p")
	end
end

app/views/greeter/goodbye.html.erb
<h1>Greeter#goodbye</h1>
<p>Find me in app/views/greeter/goodbye.html.erb</p>

<p>This is me....</p>

app/views/greeter/hello.html.erb
<h1>Greeter#hello</h1>
<p>Find me in app/views/greeter/hello.html.erb</p>
<p>The sample name is : <%= @name %></p> 
<p>And the time is: <%= @time %></p>
<p>This is custom formatted time: <%= formatted_time(@time) %></p>
<p>This page was displayed : <%= @times_displayed%> times</p>
<p>This is a link_to helper used: <%= link_to(@name, 'http://www.google.com') %> </p>
<p>This is a using _path to link to a variable : <%= link_to("goodbye", greeter_goodbye_path)%></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Week3</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>